gantt
    title Markdown-blog
    dateFormat YYYY-MM-DD
    section Design
        Design layout   :done,a1, 2023-07-28, 1d
        integrate vue and laravel    :done,a2, 2023-07-28, 1d
    section Markdown
        Collect .md to display :done,2023-07-29, 2d
        Design main page    :done,b1,2023-07-29, 2d
        Commonmark :done,after b1,2023-07-30, 1d
    section Style
        extract TOC :done, c1,2023-07-30,1d
        Add Mermaid support :done, after c1,2023-07-31, 1d
    section Features
        Add category listing :active,d1,2023-07-31,2d
